# vim: ft=ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

default_platform :android

platform :android do
  before_all do
    gradle(task: 'increaseVersionCode')
  end

  desc "Generate a Signed APK"
  lane :build do
    gradle(task: 'clean')
    gradle(task: "assemble", build_type: "Release")
  end

  desc "Build the app and deploy it to Beta"
  lane :beta do
    build
    git_add(path: "app/build.gradle")
    git_commit(path: "app/build.gradle", message: "Bump version number")
    supply(track: "beta", apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}")
  end

  desc "Build the app and deploy it to Alpha"
  lane :alpha do
    build
    git_add(path: "app/build.gradle")
    git_commit(path: "app/build.gradle", message: "Bump version number")
    supply(track: "alpha", apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}")
  end

  desc "Build the app and deploy it to Production"
  lane :release do
    build
    git_add(path: "app/build.gradle")
    git_commit(path: "app/build.gradle", message: "Bump version number")
    supply(apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}")
  end

end
